project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '/assets/**/en_us.json'
    translation: '/assets/**/%two_letters_code%_%two_letters_country_code%.json'
    languages_mapping:
      json:
        uk: uk_ua
