project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /assets/**/en_us.json
    translation: /assets/**/%locale_with_underscore%.json
    excluded_target_languages:
      - en
    skip_untranslated_strings: true
    languages_mapping:
        locale_with_underscore:
            uk: uk_ua
