project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '/assets/**/en_us.json'
    translation: '/assets/**/uk_ua.json'
    languages:
      - uk
