project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /assets/*/lang/en_us.json
    translation: /assets/*/lang/uk_ua.json
    languages_mapping:
      json:
        uk: uk_ua
