project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

languages_mapping:
  uk:
    locale_with_underscore: uk_ua

files:
  [
    {
      source: '/assets/*/lang/en_us.json',
      translation: /assets/*/lang/%locale_with_underscore%.json
      languages_mapping: {
        uk: {
          locale_with_underscore: 'uk_ua'
        }
      },
      update_option: update_as_unapproved,
      scheme: json
    }
  ]
