project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /assets/*/lang/en_us.json
    translation: '%original_path%/%locale_with_underscore%.%file_extension%'
